name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        webpack: ['5']
    name: CI
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: .nvmrc
      - run: npm install
      - run: npm install webpack@${{ matrix.webpack }}
      - run: npm run lint
      - run: npm test
